Handle HTTP errors when listing remote versions instead of succeeding with blank output

diff --git a/libexec/kopsenv-list-remote b/libexec/kopsenv-list-remote
--- a/libexec/kopsenv-list-remote
+++ b/libexec/kopsenv-list-remote
@@ -15,9 +15,26 @@ platform="$(kops_platform)"
 # returned in JSON output from the github API, but there's no other
 # reasonable way to get a list of the current kops versions using
 # only curl + POSIX tools
+
 json=$(curlw -s -L https://api.github.com/repos/kubernetes/kops/releases\?per_page=100)
 (( "$?" )) && exit $?
+http_status=$(echo "$json" | grep HTTP_RESPONSE_CODE |  awk '{print $2}')
+if [[ http_status != 2* ]]
+then
+   echo "Github API response error:
+$json"
+   exit 1
+fi 
+
 json2=$(curlw -s -L https://api.github.com/repos/spotinst/kubernetes-kops/releases\?per_page=100)
+http_status=$(echo "$json2" | grep HTTP_RESPONSE_CODE |  awk '{print $2}')
+if [[ http_status != 2* ]] 
+then 
+   echo "Github API response error:
+${json2}"
+   exit 1
+fi 
+
 (( "$?" )) && exit $?
 output="$(echo "${json}" \
   | grep 'download/[v]\?[0-9\.]\{1,\}/kops-'$platform'"' \
